# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9492291717c57adafeca7a6ba14157882db863c3187dd21db3652b285400812cbbf1a3ce68b9cc59da0c90d95d3c650c9366ec40b15b767d91cee86ea597138

test:
  secret_key_base: 7188a2703c7e830c08b45897eae02175beeff05bdd396d9357c6399ce4240c68580ffede583d25bf71e7971fb8f6dbc4fccffa627f7bb8c2a151d37b8ac54919

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
